import { useEffect, useState } from 'react';
import { api, money, toCents } from './api';
import type { Product, Sale } from './types';

type Notice = { type: 'ok' | 'error'; text: string } | null;
type Basic = { id: string; name: string; document?: string; phone?: string; email?: string; active?: boolean };

type DashboardData = { salesCount: number; revenueCents: number; ticketAverageCents: number; paymentTotals: Record<string, number>; openCashRegisters: unknown[]; lowStock: Product[]; topProducts: { product?: Product; quantity: number; totalCents: number }[] };

export function ManagementDashboard() {
  const [data, setData] = useState<DashboardData | null>(null);
  useEffect(() => { api<DashboardData>('/dashboard').then(setData); }, []);
  if (!data) return <p>Carregando dashboard...</p>;
  return <section><h1 className="font-display text-3xl font-bold">Dashboard gerencial</h1><div className="mt-5 grid gap-4 md:grid-cols-4"><Metric title="Vendas hoje" value={String(data.salesCount)} /><Metric title="Faturamento" value={money(data.revenueCents)} /><Metric title="Ticket medio" value={money(data.ticketAverageCents)} /><Metric title="Caixas abertos" value={String(data.openCashRegisters.length)} /></div><div className="mt-5 grid gap-4 xl:grid-cols-3"><Panel title="Pagamentos">{Object.entries(data.paymentTotals).map(([method, value]) => <Row key={method} cols={[method, money(value)]} />)}</Panel><Panel title="Estoque baixo">{data.lowStock.map((p) => <Row key={p.id} cols={[p.name, `${p.stockQuantity}/${p.minStock}`]} />)}</Panel><Panel title="Top produtos">{data.topProducts.map((item) => <Row key={item.product?.id} cols={[item.product?.name ?? '-', String(item.quantity), money(item.totalCents)]} />)}</Panel></div></section>;
}

function Metric({ title, value }: { title: string; value: string }) { return <div className="panel p-5"><p className="text-sm text-ink/60">{title}</p><p className="mt-2 text-2xl font-black text-moss">{value}</p></div>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <div className="panel overflow-hidden"><h2 className="border-b border-line bg-paper p-3 font-display text-lg font-bold">{title}</h2><div className="divide-y divide-line">{children}</div></div>; }
function Row({ cols }: { cols: (string | number)[] }) { return <div className="grid grid-cols-3 gap-2 px-3 py-2 text-sm">{cols.map((col, index) => <span key={index} className={index === 0 ? 'font-semibold' : ''}>{col}</span>)}</div>; }

export function EntitiesPage({ notify }: { notify: (notice: Notice) => void }) {
  const [tab, setTab] = useState<'customers' | 'suppliers' | 'employees'>('customers');
  const [rows, setRows] = useState<Basic[]>([]);
  const [form, setForm] = useState({ name: '', document: '', phone: '', email: '', address: '', roleName: 'Atendente', commissionPercent: '0' });
  async function load() { setRows(await api<Basic[]>(`/entities/${tab}`)); }
  useEffect(() => { load().catch((error) => notify({ type: 'error', text: error.message })); }, [tab]);
  async function save(event: React.FormEvent) { event.preventDefault(); const body = tab === 'employees' ? { name: form.name, document: form.document || undefined, phone: form.phone || undefined, email: form.email || undefined, roleName: form.roleName, commissionPercent: Number(form.commissionPercent || 0) } : { name: form.name, document: form.document || undefined, phone: form.phone || undefined, email: form.email || undefined, address: form.address || undefined }; await api(`/entities/${tab}`, { method: 'POST', body: JSON.stringify(body) }); notify({ type: 'ok', text: 'Cadastro salvo.' }); setForm({ name: '', document: '', phone: '', email: '', address: '', roleName: 'Atendente', commissionPercent: '0' }); await load(); }
  return <section><h1 className="font-display text-3xl font-bold">Cadastros</h1><Tabs tabs={[['customers', 'Clientes'], ['suppliers', 'Fornecedores'], ['employees', 'Funcionarios']]} active={tab} setActive={(v) => setTab(v as typeof tab)} /><form onSubmit={save} className="panel mt-4 grid gap-3 p-4 md:grid-cols-4"><input className="field" placeholder="Nome" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} required /><input className="field" placeholder="CPF/CNPJ" value={form.document} onChange={(e) => setForm({ ...form, document: e.target.value })} /><input className="field" placeholder="Telefone" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} /><input className="field" placeholder="E-mail" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} />{tab === 'employees' ? <><input className="field" placeholder="Cargo" value={form.roleName} onChange={(e) => setForm({ ...form, roleName: e.target.value })} /><input className="field" placeholder="Comissao %" value={form.commissionPercent} onChange={(e) => setForm({ ...form, commissionPercent: e.target.value })} /></> : <input className="field md:col-span-2" placeholder="Endereco" value={form.address} onChange={(e) => setForm({ ...form, address: e.target.value })} />}<button className="btn-primary md:col-span-2">Salvar cadastro</button></form><SimpleTable rows={rows.map((r) => [r.name, r.document ?? '-', r.phone ?? '-', r.email ?? '-', r.active === false ? 'Inativo' : 'Ativo'])} headers={['Nome', 'Documento', 'Telefone', 'E-mail', 'Status']} /></section>;
}

export function StockPage({ notify }: { notify: (notice: Notice) => void }) {
  const [products, setProducts] = useState<Product[]>([]); const [movements, setMovements] = useState<any[]>([]); const [form, setForm] = useState({ productId: '', type: 'IN', quantity: '1', reason: '', lot: '', expiresAt: '' }); const [counted, setCounted] = useState('');
  async function load() { const productData = await api<Product[]>('/products'); setProducts(productData); setMovements(await api<any[]>('/stock/movements')); setForm((f) => ({ ...f, productId: f.productId || productData[0]?.id || '' })); }
  useEffect(() => { load().catch((error) => notify({ type: 'error', text: error.message })); }, []);
  async function saveMovement(event: React.FormEvent) { event.preventDefault(); await api('/stock/movements', { method: 'POST', body: JSON.stringify({ ...form, quantity: Number(form.quantity), expiresAt: form.expiresAt || undefined }) }); notify({ type: 'ok', text: 'Movimentacao registrada.' }); await load(); }
  async function inventory() { await api('/stock/inventory', { method: 'POST', body: JSON.stringify({ notes: 'Inventario simples', applyAdjustments: true, items: [{ productId: form.productId, countedQuantity: Number(counted) }] }) }); notify({ type: 'ok', text: 'Inventario aplicado.' }); await load(); }
  return <section><h1 className="font-display text-3xl font-bold">Estoque avancado</h1><form onSubmit={saveMovement} className="panel mt-4 grid gap-3 p-4 md:grid-cols-6"><select className="field md:col-span-2" value={form.productId} onChange={(e) => setForm({ ...form, productId: e.target.value })}>{products.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select><select className="field" value={form.type} onChange={(e) => setForm({ ...form, type: e.target.value })}><option value="IN">Entrada</option><option value="OUT">Saida</option><option value="ADJUSTMENT">Ajuste</option><option value="LOSS">Perda</option></select><input className="field" placeholder="Quantidade" value={form.quantity} onChange={(e) => setForm({ ...form, quantity: e.target.value })} /><input className="field" placeholder="Lote" value={form.lot} onChange={(e) => setForm({ ...form, lot: e.target.value })} /><input className="field" type="date" value={form.expiresAt} onChange={(e) => setForm({ ...form, expiresAt: e.target.value })} /><input className="field md:col-span-4" placeholder="Motivo" value={form.reason} onChange={(e) => setForm({ ...form, reason: e.target.value })} required /><button className="btn-primary md:col-span-2">Registrar movimento</button></form><div className="panel mt-4 grid gap-3 p-4 md:grid-cols-3"><input className="field" placeholder="Contagem para inventario" value={counted} onChange={(e) => setCounted(e.target.value)} /><button className="btn-secondary md:col-span-2" onClick={inventory}>Aplicar inventario do produto selecionado</button></div><SimpleTable headers={['Data', 'Produto', 'Tipo', 'Qtd', 'Motivo']} rows={movements.map((m) => [new Date(m.createdAt).toLocaleString('pt-BR'), m.product?.name ?? '-', m.type, String(m.quantity), m.reason])} /></section>;
}

export function PurchasesPage({ notify }: { notify: (notice: Notice) => void }) {
  const [suppliers, setSuppliers] = useState<Basic[]>([]); const [products, setProducts] = useState<Product[]>([]); const [orders, setOrders] = useState<any[]>([]); const [form, setForm] = useState({ supplierId: '', productId: '', quantity: '1', cost: '1', notes: '' });
  async function load() { const [s, p, o] = await Promise.all([api<Basic[]>('/entities/suppliers'), api<Product[]>('/products'), api<any[]>('/purchases')]); setSuppliers(s); setProducts(p); setOrders(o); setForm((f) => ({ ...f, supplierId: f.supplierId || s[0]?.id || '', productId: f.productId || p[0]?.id || '' })); }
  useEffect(() => { load().catch((error) => notify({ type: 'error', text: error.message })); }, []);
  async function create(event: React.FormEvent) { event.preventDefault(); await api('/purchases', { method: 'POST', body: JSON.stringify({ supplierId: form.supplierId, notes: form.notes, items: [{ productId: form.productId, quantity: Number(form.quantity), costPriceCents: toCents(form.cost) }] }) }); notify({ type: 'ok', text: 'Pedido criado.' }); await load(); }
  async function receive(id: string) { await api(`/purchases/${id}/receive`, { method: 'POST' }); notify({ type: 'ok', text: 'Compra recebida e estoque atualizado.' }); await load(); }
  return <section><h1 className="font-display text-3xl font-bold">Compras</h1><form onSubmit={create} className="panel mt-4 grid gap-3 p-4 md:grid-cols-5"><select className="field" value={form.supplierId} onChange={(e) => setForm({ ...form, supplierId: e.target.value })}>{suppliers.map((s) => <option key={s.id} value={s.id}>{s.name}</option>)}</select><select className="field" value={form.productId} onChange={(e) => setForm({ ...form, productId: e.target.value })}>{products.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select><input className="field" placeholder="Qtd" value={form.quantity} onChange={(e) => setForm({ ...form, quantity: e.target.value })} /><input className="field" placeholder="Custo" value={form.cost} onChange={(e) => setForm({ ...form, cost: e.target.value })} /><button className="btn-primary">Criar pedido</button><input className="field md:col-span-5" placeholder="Observacao" value={form.notes} onChange={(e) => setForm({ ...form, notes: e.target.value })} /></form><div className="panel mt-4 overflow-auto"><table className="w-full min-w-[720px]"><thead className="bg-paper"><tr><th className="table-cell">Fornecedor</th><th className="table-cell">Status</th><th className="table-cell">Total</th><th className="table-cell">Itens</th><th className="table-cell">Acoes</th></tr></thead><tbody>{orders.map((o) => <tr key={o.id} className="border-t border-line"><td className="table-cell">{o.supplier?.name ?? '-'}</td><td className="table-cell">{o.status}</td><td className="table-cell">{money(o.totalCents)}</td><td className="table-cell">{o.items?.length ?? 0}</td><td className="table-cell">{o.status === 'OPEN' && <button className="btn-secondary" onClick={() => receive(o.id)}>Receber</button>}</td></tr>)}</tbody></table></div></section>;
}

export function CommercialPage({ notify }: { notify: (notice: Notice) => void }) {
  const [products, setProducts] = useState<Product[]>([]); const [customers, setCustomers] = useState<Basic[]>([]); const [promotions, setPromotions] = useState<any[]>([]); const [credits, setCredits] = useState<any[]>([]); const [form, setForm] = useState({ productId: '', description: 'Promocao semanal', discountPercent: '5', customerId: '', credit: '50' });
  async function load() { const [p, c, pro, cr] = await Promise.all([api<Product[]>('/products'), api<Basic[]>('/entities/customers'), api<any[]>('/commercial/promotions'), api<any[]>('/commercial/credits')]); setProducts(p); setCustomers(c); setPromotions(pro); setCredits(cr); setForm((f) => ({ ...f, productId: f.productId || p[0]?.id || '', customerId: f.customerId || c[0]?.id || '' })); }
  useEffect(() => { load().catch((error) => notify({ type: 'error', text: error.message })); }, []);
  async function promotion() { await api('/commercial/promotions', { method: 'POST', body: JSON.stringify({ productId: form.productId, description: form.description, discountPercent: Number(form.discountPercent), startsAt: new Date().toISOString(), endsAt: new Date(Date.now() + 7 * 86400000).toISOString(), active: true }) }); notify({ type: 'ok', text: 'Promocao criada.' }); await load(); }
  async function credit() { await api('/commercial/credits', { method: 'POST', body: JSON.stringify({ customerId: form.customerId, amountCents: toCents(form.credit) }) }); notify({ type: 'ok', text: 'Fiado/convenio registrado.' }); await load(); }
  return <section><h1 className="font-display text-3xl font-bold">Comercial</h1><div className="mt-4 grid gap-4 lg:grid-cols-2"><div className="panel p-4"><h2 className="font-display text-xl font-bold">Promocoes</h2><select className="field mt-3" value={form.productId} onChange={(e) => setForm({ ...form, productId: e.target.value })}>{products.map((p) => <option key={p.id} value={p.id}>{p.name}</option>)}</select><input className="field mt-3" value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} /><input className="field mt-3" value={form.discountPercent} onChange={(e) => setForm({ ...form, discountPercent: e.target.value })} placeholder="%" /><button className="btn-primary mt-3 w-full" onClick={promotion}>Criar promocao</button>{promotions.map((p) => <Row key={p.id} cols={[p.description, `${p.discountPercent ?? 0}%`, p.active ? 'Ativa' : 'Inativa']} />)}</div><div className="panel p-4"><h2 className="font-display text-xl font-bold">Fiado / convenio</h2><select className="field mt-3" value={form.customerId} onChange={(e) => setForm({ ...form, customerId: e.target.value })}>{customers.map((c) => <option key={c.id} value={c.id}>{c.name}</option>)}</select><input className="field mt-3" value={form.credit} onChange={(e) => setForm({ ...form, credit: e.target.value })} /><button className="btn-primary mt-3 w-full" onClick={credit}>Registrar credito</button>{credits.map((c) => <Row key={c.id} cols={[c.customer?.name ?? '-', money(c.amountCents), c.status]} />)}</div></div></section>;
}

export function ReportsPlusPage({ notify }: { notify: (notice: Notice) => void }) {
  const [sales, setSales] = useState<Sale[]>([]); const [margin, setMargin] = useState<any[]>([]); const [noMove, setNoMove] = useState<Product[]>([]); const [receipt, setReceipt] = useState<Sale | null>(null);
  async function load() { const [s, m, n] = await Promise.all([api<Sale[]>('/sales'), api<any[]>('/reports/margin'), api<Product[]>('/reports/no-movement-products?days=30')]); setSales(s); setMargin(m); setNoMove(n); }
  useEffect(() => { load().catch((error) => notify({ type: 'error', text: error.message })); }, []);
  async function cancelSale(id: string) { await api(`/sales/${id}/cancel`, { method: 'POST', body: JSON.stringify({ reason: 'Cancelamento operacional' }) }); notify({ type: 'ok', text: 'Venda cancelada e estoque estornado.' }); await load(); }
  return <section><h1 className="font-display text-3xl font-bold">Relatorios e vendas</h1><div className="mt-4 grid gap-4 xl:grid-cols-2"><div className="panel overflow-auto"><h2 className="p-4 font-display text-xl font-bold">Vendas</h2><table className="w-full min-w-[760px]"><tbody>{sales.map((s) => <tr key={s.id} className="border-t border-line"><td className="table-cell">{s.id.slice(-6)}</td><td className="table-cell">{new Date(s.createdAt).toLocaleString('pt-BR')}</td><td className="table-cell">{money(s.netTotalCents)}</td><td className="table-cell">{s.status}</td><td className="table-cell"><button className="btn-secondary mr-2" onClick={() => setReceipt(s)}>Cupom</button>{s.status !== 'CANCELED' && <button className="btn-danger" onClick={() => cancelSale(s.id)}>Cancelar</button>}</td></tr>)}</tbody></table></div><Panel title="Margem por produto">{margin.map((m) => <Row key={m.product.id} cols={[m.product.name, money(m.revenueCents), money(m.marginCents)]} />)}</Panel><Panel title="Sem giro 30 dias">{noMove.map((p) => <Row key={p.id} cols={[p.name, String(p.stockQuantity), money(p.salePriceCents)]} />)}</Panel>{receipt && <Receipt sale={receipt} onClose={() => setReceipt(null)} />}</div></section>;
}

export function AuditPage() { const [logs, setLogs] = useState<any[]>([]); useEffect(() => { api<any[]>('/audit').then(setLogs); }, []); return <section><h1 className="font-display text-3xl font-bold">Auditoria</h1><SimpleTable headers={['Data', 'Acao', 'Entidade', 'ID']} rows={logs.map((l) => [new Date(l.createdAt).toLocaleString('pt-BR'), l.action, l.entity, l.entityId ?? '-'])} /></section>; }

function Receipt({ sale, onClose }: { sale: Sale; onClose: () => void }) { return <div className="panel p-5"><div className="mx-auto max-w-sm bg-white p-4 font-mono text-sm text-black"><h2 className="text-center font-bold">CUPOM NAO FISCAL</h2><p>Venda: {sale.id}</p><p>Data: {new Date(sale.createdAt).toLocaleString('pt-BR')}</p><hr className="my-2" />{sale.items?.map((item) => <p key={item.product.id}>{item.product.name} {item.quantity} x {money(item.unitPriceCents)} = {money(item.subtotalCents)}</p>)}<hr className="my-2" /><p>Desconto: {money(sale.discountTotalCents)}</p><p className="font-bold">Total: {money(sale.netTotalCents)}</p><p className="mt-3 text-center">SEM VALOR FISCAL</p></div><div className="mt-3 flex gap-2"><button className="btn-primary" onClick={() => window.print()}>Imprimir</button><button className="btn-secondary" onClick={onClose}>Fechar</button></div></div>; }

function Tabs({ tabs, active, setActive }: { tabs: string[][]; active: string; setActive: (v: string) => void }) { return <div className="mt-4 flex gap-2 overflow-x-auto">{tabs.map(([id, label]) => <button key={id} className={active === id ? 'btn-primary' : 'btn-secondary'} onClick={() => setActive(id)}>{label}</button>)}</div>; }
function SimpleTable({ headers, rows }: { headers: string[]; rows: (string | number)[][] }) { return <div className="panel mt-4 overflow-auto"><table className="w-full min-w-[680px]"><thead className="bg-paper"><tr>{headers.map((h) => <th key={h} className="table-cell">{h}</th>)}</tr></thead><tbody>{rows.map((row, index) => <tr key={index} className="border-t border-line">{row.map((cell, cellIndex) => <td key={cellIndex} className="table-cell">{cell}</td>)}</tr>)}</tbody></table></div>; }
